/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author toshibapc
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        rdCiudadano = new javax.swing.JMenu();
        jrCiudadano = new javax.swing.JRadioButtonMenuItem();
        jrIndigena = new javax.swing.JRadioButtonMenuItem();
        jrMigrante = new javax.swing.JRadioButtonMenuItem();
        jrRefugiado = new javax.swing.JRadioButtonMenuItem();
        jrPlantillaPersona = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jrPlantillaPais = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rdCiudadano.setText("Persona");

        jrCiudadano.setSelected(true);
        jrCiudadano.setText("Ciudadano");
        rdCiudadano.add(jrCiudadano);

        jrIndigena.setSelected(true);
        jrIndigena.setText("Indigena");
        jrIndigena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrIndigenaActionPerformed(evt);
            }
        });
        rdCiudadano.add(jrIndigena);

        jrMigrante.setSelected(true);
        jrMigrante.setText("Migrante");
        rdCiudadano.add(jrMigrante);

        jrRefugiado.setSelected(true);
        jrRefugiado.setText("Refugiado");
        jrRefugiado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrRefugiadoActionPerformed(evt);
            }
        });
        rdCiudadano.add(jrRefugiado);

        jrPlantillaPersona.setSelected(true);
        jrPlantillaPersona.setText("Plantilla");
        rdCiudadano.add(jrPlantillaPersona);

        jMenuBar1.add(rdCiudadano);

        jMenu2.setText("País");

        jrPlantillaPais.setSelected(true);
        jrPlantillaPais.setText("Plantilla");
        jMenu2.add(jrPlantillaPais);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrIndigenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrIndigenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrIndigenaActionPerformed

    private void jrRefugiadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrRefugiadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrRefugiadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jrCiudadano;
    private javax.swing.JRadioButtonMenuItem jrIndigena;
    private javax.swing.JRadioButtonMenuItem jrMigrante;
    private javax.swing.JRadioButtonMenuItem jrPlantillaPais;
    private javax.swing.JRadioButtonMenuItem jrPlantillaPersona;
    private javax.swing.JRadioButtonMenuItem jrRefugiado;
    private javax.swing.JMenu rdCiudadano;
    // End of variables declaration//GEN-END:variables
}
